# Generated by Django 5.0.7 on 2024-08-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'ordering': ['title'], 'verbose_name': 'Trợ giúp', 'verbose_name_plural': 'Trợ giúp'},
        ),
        migrations.AlterModelOptions(
            name='helpcategory',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục trợ giúp', 'verbose_name_plural': 'Danh mục trợ giúp'},
        ),
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help.helpcategory', verbose_name='Danh mục trợ giúp'),
        ),
        migrations.AlterField(
            model_name='help',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
