# Generated by Django 5.0.7 on 2024-08-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0003_alter_help_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="help",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helps",
                to="help.helpcategory",
            ),
        ),
    ]
