# Generated by Django 5.0.7 on 2024-08-04 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_alter_booking_options_alter_field_options_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Thanh toán'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.booking', verbose_name='Đặt sân bóng'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='channel',
            field=models.CharField(choices=[('momo', 'Momo'), ('vn_pay', 'VNPay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Thành công'), ('pending', 'Đang thanh toán'), ('failed', 'Không thành công')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50),
        ),
    ]
