# Generated by Django 5.0.7 on 2024-08-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0006_booking_paid_alter_booking_field_alter_booking_user_and_more"),
        ("payment", "0002_alter_payment_options_alter_payment_booking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="field.booking"
            ),
        ),
    ]
