# Generated by Django 5.0.7 on 2024-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_payment_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="reference_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
