# Generated by Django 5.0.7 on 2024-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Hỗ trợ khách hàng',
                'verbose_name_plural': 'Hỗ trợ khách hàng',
                'ordering': ['service_name'],
            },
        ),
        migrations.DeleteModel(
            name='CustomerService',
        ),
        migrations.AlterModelOptions(
            name='introduction',
            options={'ordering': ['-created_date'], 'verbose_name': 'Giới thiệu', 'verbose_name_plural': 'Giới thiệu'},
        ),
    ]
