# Generated by Django 5.0.7 on 2024-08-04 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0005_alter_field_status_alter_fieldstatushistory_status"),
        ("review", "0002_alter_review_options_alter_review_football_field_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("user", "football_field")},
        ),
    ]
