# Generated by Django 5.0.7 on 2024-08-04 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
        migrations.AlterModelOptions(
            name='notificationcontent',
            options={'verbose_name': 'Nội dung thông báo', 'verbose_name_plural': 'Nội dung thông báo'},
        ),
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'verbose_name': 'Người nhận thông báo', 'verbose_name_plural': 'Người nhận thông báo'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='status',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient_type',
        ),
        migrations.RemoveField(
            model_name='notificationcontent',
            name='name',
        ),
        migrations.AddField(
            model_name='notification',
            name='send_type',
            field=models.CharField(choices=[('unicast', 'Unicast'), ('multicast', 'Multicast'), ('broadcast', 'Broadcast')], default='unicast', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationcontent', verbose_name='Nội dung thông báo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi'),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='entity_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='entity_type',
            field=models.CharField(choices=[('booking', 'Đã đặt sân'), ('review', 'Đã đánh giá'), ('review_edit', 'Chỉnh sửa đánh giá')], max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='notification_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationcontent', verbose_name=' Nội dung thông báo'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=' Người nhận thông báo'),
        ),
    ]
