# Generated by Django 5.0.7 on 2024-08-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcontent",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("booking", "Đã đặt sân"),
                    ("review", "Đã đánh giá sân"),
                    ("review_edit", "Chỉnh sửa đánh giá sân"),
                ],
                max_length=255,
            ),
        ),
    ]
