# Generated by Django 5.0.7 on 2024-08-13 10:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notificationsender_delete_notificationrecipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_type',
            field=models.CharField(choices=[('USER', 'Người dùng'), ('ADMIN', 'Ban quản trị'), ('CUSTOMER', 'Khách hàng'), ('CUSTOMERS', 'Nhiều khách hàng'), ('ALL', 'Tất cả')], default='USER', max_length=20),
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=163, unique=True, validators=[django.core.validators.MinLengthValidator(163)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
