# Generated by Django 5.0.7 on 2024-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_send_type_fcmtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationcontent",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("booking", "Đã đặt sân"),
                    ("confirm_booking", "Chúc mừng bạn đã đăt sân thành công"),
                    ("review", "Đã đánh giá sân"),
                    ("review_edit", "Chỉnh sửa đánh giá sân"),
                ],
                max_length=255,
            ),
        ),
    ]
