# Generated by Django 5.0.7 on 2024-08-04 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Đặt sân bóng', 'verbose_name_plural': 'Đặt sân bóng'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Sân bóng', 'verbose_name_plural': 'Sân bóng'},
        ),
        migrations.AlterModelOptions(
            name='fieldstatushistory',
            options={'verbose_name': 'Lịch sử trạng thái sân bóng', 'verbose_name_plural': 'Lịch sử trạng thái sân bóng'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='football_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='Sân được đặt'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('5', 'sân 5'), ('7', 'sân 7'), ('11', 'sân 11')], default='5', max_length=20),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[('available', 'TRỐNG'), ('booked', 'ĐÃ ĐẶT'), ('maintenance', 'ĐANG BẢO TRÌ')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldstatushistory',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fieldstatushistory',
            name='football_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='Sân được bảo trì'),
        ),
        migrations.AlterField(
            model_name='fieldstatushistory',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fieldstatushistory',
            name='status',
            field=models.CharField(choices=[('available', 'TRỐNG'), ('booked', 'ĐÃ ĐẶT'), ('maintenance', 'ĐANG BẢO TRÌ')], max_length=20),
        ),
    ]
