# Generated by Django 5.0.7 on 2024-08-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_alter_booking_options_alter_field_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='football_field',
            new_name='field',
        ),
    ]
