# Generated by Django 5.0.7 on 2024-08-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0003_rename_football_field_booking_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="field_type",
            field=models.CharField(
                choices=[("5", "Sân 5"), ("7", "Sân 7"), ("11", "Sân 11")],
                default="5",
                max_length=20,
            ),
        ),
    ]
