# Generated by Django 5.0.7 on 2024-08-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0004_alter_field_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "TRỐNG"),
                    ("Booked", "ĐÃ ĐẶT"),
                    ("Maintenance", "ĐANG BẢO TRÌ"),
                ],
                default="Available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fieldstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "TRỐNG"),
                    ("Booked", "ĐÃ ĐẶT"),
                    ("Maintenance", "ĐANG BẢO TRÌ"),
                ],
                max_length=20,
            ),
        ),
    ]
