# Generated by Django 5.0.7 on 2024-08-04 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0005_alter_field_status_alter_fieldstatushistory_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="field.field"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="fieldstatushistory",
            name="football_field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="field.field"
            ),
        ),
    ]
