# Generated by Django 5.0.7 on 2024-08-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0006_booking_paid_alter_booking_field_alter_booking_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldstatushistory",
            old_name="football_field",
            new_name="field",
        ),
    ]
