# Generated by Django 5.0.7 on 2024-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0010_alter_field_status_alter_fieldstatushistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(),
        ),
    ]
